GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTc0Mjk3NTYzNywiZXhwIjoxNzQyOTc1NjUyfQ.y804V04fYPR5Vxnh1r1h2RboOA94ZLWh2y1rLHZXZVM



###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTc0Mjk3NTQ5N30.04w1FjIQJSRN31qaJokLP9_PtfEbBG8mTUNPb7vhlTI"
}


###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiIsImlhdCI6MTc0Mjk3NTQ5N30.04w1FjIQJSRN31qaJokLP9_PtfEbBG8mTUNPb7vhlTI"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "John"
}